from __future__ import annotations


EXCHANGE = "binance"
SYMBOL = "BTCUSDT"
HOURLY_TIMEFRAME = "1h"
ZONE_TIMEFRAME = "4h"
DETECTOR_VERSION = "support_structure_v1"
STRATEGY_VERSION = "support_close_v1"
FINGERPRINT_VERSION = "zf1"

ONE_HOUR_MS = 3_600_000
FOUR_HOURS_MS = 14_400_000
ONE_DAY_MS = 86_400_000
LOOKBACK_48H_MS = 48 * ONE_HOUR_MS
COOLDOWN_24H_MS = 24 * ONE_HOUR_MS
